package constant;

public enum OmokPacketCode {
    REQ_SIGNUP, ACK_SIGNUP, REQ_LOGIN, ACK_LOGIN, REQ_RECORD, ACK_RECORD, REQ_MATCHING, ACK_MATCHING,
    REQ_PUTSTONE, ACK_PUTSTONE, REQ_SURREN, ACK_SURREN, REQ_RESULT, ACK_RESULT
}
